WebUI/Controllers/DictionaryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class DictionaryController : BaseController
    {
        public IActionResult Index() => View();
    }
}

WebUI/Controllers/StructuralUnitController.cs
using Application.MediatR.StructuralUnits.Commands.CreateStructuralUnit;
using Application.MediatR.StructuralUnits.Commands.DeleteStructuralUnit;
using Application.MediatR.StructuralUnits.Commands.EditStructuralUnit;
using Application.MediatR.StructuralUnits.Queries.GetStructuralUnits;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace WebUI.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StructuralUnitController : BaseController
    {
        public async Task<IActionResult> Index()
        {
            var StructuralUnits = await Mediator.Send(new GetStructuralUnitsQuery());
            return View(StructuralUnits);
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateStructuralUnitCommand command)
        {
            if (!ModelState.IsValid)
                return View(command);

            var result = await Mediator.Send(command);
            TempData["IsUpdated"] = result.Succeeded;

            if (!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, result.Errors.ToString());
                return View(command);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var StructuralUnit = await Mediator.Send(new GetStructuralUnitByIdQuery { Id = id });

            var editStructuralUnitCommand = new EditStructuralUnitCommand
            {
                Id = StructuralUnit.Id,
                Name = StructuralUnit.Name
            };

            return View(editStructuralUnitCommand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditStructuralUnitCommand command)
        {
            if (!ModelState.IsValid)
                return View(command);

            var result = await Mediator.Send(command);
            TempData["IsUpdated"] = result.Succeeded;

            if (!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, result.Errors.ToString());
                return View(command);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteStructuralUnitCommand command)
        {
            var result = await Mediator.Send(command);

            if (!result.Succeeded)
                return BadRequest(result.Errors.ToString());

            return Ok();
        }
    }
}

WebUI/Views/StructuralUnit/Create.cshtml
@model CreateStructuralUnitCommand

@{
    ViewData["Title"] = "Добавить запись";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Справочники</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a asp-controller="Home" asp-action="Index">На главную</a>
            </li>
            <li class="breadcrumb-item">
                <a asp-controller="Dictionary" asp-action="Index">Список справочников</a>
            </li>
            <li class="breadcrumb-item">
                <a asp-action="Index">Список мэрий</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Добавить запись</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox">
        <div class="ibox-content">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <h2>Новая запись</h2>

            <form asp-action="Create">

                <div class="hr-line-dashed"></div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Название</label>
                    <div class="col-sm-7">
                        <input asp-for="@Model.Name" class="form-control bg-light">
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="hr-line-dashed"></div>

                <div class="form-group row">
                    <div class="col-sm-4 col-sm-offset-2">
                        <a asp-action="Index" class="btn btn-white" type="button">
                            <i class="mdi mdi-arrow-left-bold-circle-outline"></i> Отмена
                        </a>
                        <button class="btn btn-info" type="submit">
                            <i class="mdi mdi-content-save"></i> Сохранить
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

@section Scripts {
    @Html.RenderPartialAsync("_ValidationScriptsPartial")
}

WebUI/Views/StructuralUnit/Edit.cshtml
@model EditStructuralUnitCommand

@{
    ViewData["Title"] = "Изменить запись";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Справочники</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a asp-controller="Home" asp-action="Index">На главную</a>
            </li>
            <li class="breadcrumb-item">
                <a asp-controller="Dictionary" asp-action="Index">Список справочников</a>
            </li>
            <li class="breadcrumb-item">
                <a asp-action="Index">Список мэрий</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Изменить запись</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox">
        <div class="ibox-content">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <h2>Изменить запись</h2>

            <form asp-action="Edit">

                <div class="hr-line-dashed"></div>

                <input type="hidden" asp-for="@Model.Id" />

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Название</label>
                    <div class="col-sm-7">
                        <input asp-for="@Model.Name" class="form-control bg-light">
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="hr-line-dashed"></div>

                <div class="form-group row">
                    <div class="col-sm-4 col-sm-offset-2">
                        <a asp-action="Index" class="btn btn-white" type="button">
                            <i class="mdi mdi-arrow-left-bold-circle-outline"></i> Отмена
                        </a>
                        <button class="btn btn-info" type="submit">
                            <i class="mdi mdi-content-save"></i> Сохранить
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

@section Scripts {
    @Html.RenderPartialAsync("_ValidationScriptsPartial")
}

WebUI/Views/StructuralUnit/Index.cshtml
@model IList<StructuralUnitDto>

@{
    ViewData["Title"] = "Список структурных подразделений";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Справочники</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a asp-controller="Home" asp-action="Index">На главную</a>
            </li>
            <li class="breadcrumb-item">
                <a asp-controller="Dictionary" asp-action="Index">Список справочников</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>@ViewData["Title"]</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <a asp-action="Create" class="btn btn-lg btn-primary" type="button">
        Новая запись
    </a>

    <div class="ibox mt-3">
        <div class="ibox-content">

            @if (Model.Any())
            {
                <table class="footable table table-stripped toggle-arrow-tiny mt-4" data-page-size="@Model.Count">
                    <thead>
                        <tr>
                            <th data-toggle="true">#</th>
                            <th>Название</th>
                            <th class="text-white"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Count; i++)
                        {
                            <tr>
                                <td>@(i + 1)</td>
                                <td>@Model[i].Name</td>
                                <td class="text-right">
                                    <a asp-action="Edit" asp-route-id="@Model[i].Id" class="btn btn-white btn-circle" title="Изменить">
                                        <i class="mdi mdi-pencil"></i>
                                    </a>
                                    <button type="button" class="btn btn-white btn-circle delete-alert" title="Удалить"
                                            data-itemid="@Model[i].Id">
                                        <i class="mdi mdi-trash-can text-secondary"></i>
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-warning">
                    @ViewData["Title"] не заполнен.
                </div>
            }
        </div>
    </div>
</div>

@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/footable/css/footable.core.min.css" />
    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/footable/dist/footable.all.min.js"></script>
        <script src="~/js/views/structuralUnit/index.js"></script>
    </environment>
}